config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  user_name       :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base

  attr_reader :password

  validates :user_name, :session_token, presence: true
  validates :password_digest, presence: { message: "Password can't be blank" }
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :assign_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(user_name, password)
    user = User.where(user_name: user_name).first
    return nil if user.nil?
    if user.is_password?(password)
      return user
    else
      return nil
    end
  end

  has_many :cat_rental_requests

  has_many(
    :cats,
    class_name: 'Cat',
    foreign_key: :user_id,
    primary_key: :id
  )

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private

  def assign_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :redirect_logged_in_users!


  def show

  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to cats_url
      #redirect_to user_url(@user)
    else
      render :new
    end
  end

  def edit

  end

  def update

  end


  def destroy

  end

  private
  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/views/users/_req_tr.html.erb
<tr>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td>
    <% if req.pending? %>
        <%= button_to "Approve", approve_cat_rental_request_url(req) %>
        <%= button_to "Deny", deny_cat_rental_request_url(req) %>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>
</tr>

app/views/users/_user_form.html.erb
<p>
  <%= user.errors.full_messages %>
</p>
<% action = user.persisted? ? user_url(user) : users_url %>
<% method = user.persisted? ? "patch" : "post" %>
<% message = (user.persisted? ? "Update user" : "Create user") %>
<form action="<%= action %>" method="post">
<input type="hidden" name="_method" value="<%= method %>">
<input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
<label for="user_name">User name</label>
<input id="user_name" type="text" name="user[user_name]" value="<%= user.user_name %>">
<br>
<label for="password">Password</label>
<input id="password" type="password" name="user[password]">
<br>
<button><%= message %></button>
</form>

app/views/users/new.html.erb
<h1>Create new user</h1>
<%= render "user_form", user: @user %>
<a href="<%= new_session_url %>"><button>Log In</button></a>

app/views/users/show.html.erb
<% user = current_user %>

<h1><%= user.user_name %></h1>

<p>Hello, dear user!</p>