config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           not null
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer          not null
#

class CatRentalRequest < ActiveRecord::Base
  STATUS_STATES = %w(APPROVED DENIED PENDING)

  belongs_to :cat
  belongs_to :user

  after_initialize :assign_pending_status

  validates(
    :cat_id,
    :user_id,
    :end_date,
    :start_date,
    :status,
    presence: true
  )
  validates :status, inclusion: STATUS_STATES
  validate :start_must_come_before_end
  validate :does_not_overlap_approved_request

  def approve!
    raise "not pending" unless self.status == "PENDING"
    transaction do
      self.status = "APPROVED"
      self.save!

      # when we approve this request, we reject all other overlapping
      # requests for this cat.
      overlapping_pending_requests.update_all(status: 'DENIED')
    end
  end

  def approved?
    self.status == "APPROVED"
  end

  def denied?
    self.status == "DENIED"
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def pending?
    self.status == "PENDING"
  end

  private
  def assign_pending_status
    self.status ||= "PENDING"
  end

  def overlapping_requests
    CatRentalRequest
      .where("(:id IS NULL) OR (id != :id)", id: self.id)
      .where(cat_id: cat_id)
      .where(<<-SQL, start_date: start_date, end_date: end_date)
       NOT( (start_date > :end_date) OR (end_date < :start_date) )
    SQL
  end

  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end

  def overlapping_pending_requests
    overlapping_requests.where("status = 'PENDING'")
  end

  def does_not_overlap_approved_request
    # A denied request doesn't need to be checked. A pending request
    # should be checked; users shouldn't be able to make requests for
    # periods during which a cat has already been spoken for.
    return if self.denied?

    unless overlapping_approved_requests.empty?
      errors[:base] <<
        "Request conflicts with existing approved request"
    end
  end

  def start_must_come_before_end
    return if start_date < end_date
    errors[:start_date] << "must come before end date"
    errors[:end_date] << "must come after start date"
  end

end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  before_action :require_current_user!
  before_action :require_owner!, except: [:new, :create, :show]

  def approve
    current_cat_rental_request.approve!
    redirect_to cat_url(current_cat)
  end

  def deny
    current_cat_rental_request.deny!
    redirect_to cat_url(current_cat)
  end

  def new
    @request = CatRentalRequest.new
    render :new
  end

  def create
    @request = CatRentalRequest.new(cat_rental_requests_params)
    @request.user_id = current_user.id
    if @request.save
      redirect_to cat_url(@request.cat)
    else
      flash.now[:errors] = @request.errors.full_messages
      render :new
    end
  end

  def show
    @request = CatRentalRequest.find(params[:id])
  end


  private
  def current_cat_rental_request
    @request ||=
      CatRentalRequest.includes(:cat).find(params[:id])
  end

  def current_cat
    current_cat_rental_request.cat
  end

  def cat_rental_requests_params
    params.require(:request).permit(:cat_id, :start_date, :end_date, :status)
  end

  def require_owner!
    request = CatRentalRequest.find(params[:id])
    unless request.cat.user_id == current_user.id
      flash[:error] = "You do not have permission to do that."
      redirect_to cats_url
    end
  end
end

app/views/cat_rental_requests/new.html.erb
<h1>New Rental</h1>
<p>
  <%= @request.errors.full_messages %>
</p>

<% action = @request.persisted? ? cat_rental_request_url(@request) : cat_rental_requests_url(params[:id]) %>
<form action="<%= action %>" method="post">
  <% if @request.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <label for="cat_select">Choose a cat</label>
  <select id="cat_select" name="request[cat_id]">
    <option></option>
    <% Cat.all.each do |cat| %>
    <option value="<%= cat.id %>" <%= "selected" if @request.cat_id == cat.id %> >
      <%= cat.name %>
    </option>
    <% end %>
  </select>
  <br>

  <label for="request_start_date">Rental Start Date</label>
  <input type="date" id="request_start_date" name="request[start_date]"
    value="<%= @request.start_date %>">
  <br>

  <label for="request_end_date">Rental End Date</label>
  <input type="date" id="request_end_date" name="request[end_date]"
    value="<%= @request.end_date %>">
  <br>
  <button>Submit</button>
</form>