config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end
  resources :users, only: [:create, :new, :show]
  resource :session, only: [:new, :create, :destroy]
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer          not null
#

class Cat < ActiveRecord::Base

  CAT_COLORS = [
    "Black",
    "Orange",
    "Calico",
    "Hazel",
    "White",
    "Gray",
    "Multicolored",
    "Hairless"
  ]

  validates :color, presence: true, inclusion: { in: CAT_COLORS }
  validates :sex, presence: true, inclusion: { in: ["M", "F"] }
  validates :name, presence: true

  has_many(
    :cat_rental_requests,
    class_name: 'CatRentalRequest',
    foreign_key: :cat_id,
    primary_key: :id,
    dependent: :destroy
  )

  belongs_to(
    :owner,
    class_name: 'User',
    foreign_key: :user_id,
    primary_key: :id
  )

  def age
    return false if birth_date.nil?
    ((Date.today - birth_date) / 365).to_i
  end



end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  before_action :require_current_user!
  before_action :require_owner!, except: [:index, :new, :create, :show]
  def index
    @cats = Cat.all
    render :index
  end

  def new
    #dummy object
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy!

    redirect_to cats_url
  end


  private
  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end

end

app/views/cats/_form.html.erb
<p>
  <%= @cat.errors.full_messages %>
</p>
<% action = @cat.persisted? ? cat_url(@cat) : cats_url %>
<form action="<%= action %>" method="post">
  <% if @cat.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  <label for="cat_name">Cat name:</label>
  <input id="cat_name" type="text" name="cat[name]" value="<%= @cat.name %>">
  <br>

  Cat sex:
  <br>
  <input id="cat_sex_female" type="radio" name="cat[sex]" value="F"
    <%= "checked" if @cat.sex == "F" %> >
  <label for="cat_sex_female">Female</label>
  <br>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M"
    <%= "checked" if @cat.sex == "M" %> >
  <label for="cat_sex_male">Male</label>
  <br>

  <label for="cat_color">Cat Color</label>
  <select id="cat_color" name="cat[color]">
    <option></option>
    <% @cat.class::CAT_COLORS.each do |color| %>
    <option value="<%= color %>" <%= "selected" if @cat.color == color %> >
      <%= color %>
    </option>
    <% end %>
  </select>
  <br>

  <label for="cat_birth_date">Cat Birthdate</label>
  <input type="date" id="cat_birth_date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  <br>

  <label for="cat_description">Cat Description</label>
  <textarea id="cat_description" name="cat[description]"><%= @cat.description %></textarea>
  <br>

  <button>Submit</button>
</form>

app/views/cats/_req_tr.html.erb
<tr>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td>
    <% if req.pending? %>
      <% if req.cat.user_id == current_user.id %>
        <%= button_to "Approve", approve_cat_rental_request_url(req) %>
        <%= button_to "Deny", deny_cat_rental_request_url(req) %>
      <% else %>
        <%= req.status %>
      <% end %>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>

  <td>
    <% requestor = User.find(req.user_id) %>
    <%= requestor.user_name.capitalize %>
  </td>


</tr>

app/views/cats/edit.html.erb
<h1>Edit Cat</h1>
<%= render "form" %>

app/views/cats/index.html.erb
<h1>ALL THE CATS!</h1>
<ul>
  <% unless @cats.empty? %>
    <% @cats.each do |cat| %>
    <li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>
    <% end %>
  <% end %>
</ul>

app/views/cats/new.html.erb
<h1>New Cat</h1>
<%= render "form" %>

app/views/cats/show.html.erb
<h1><%= @cat.name.capitalize %></h1>

<table>
  <th>Attributes: </th>
  <tr>
    <td>Color: </td><td><%= @cat.color.capitalize  %></td>
  </tr>
  <tr>
    <td>Sex:  </td><td><%= @cat.sex %></td>
  </tr>
  <tr>
    <% @cat.birth_date == nil ? age = "unknown" : age = @cat.age.to_s + " years old" %>
    <td>Age:  </td><td><%= age %></td>
  </tr>
</table>
<br>
<strong>Description:</strong>
<br>
<p><%= @cat.description %></p>
<br>
<%= link_to "Edit #{@cat.name}", edit_cat_url(@cat) %>

<h2>Rental Requests</h2>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Status</th>
    <th>Requestor</th>
  </tr>
  <% @cat.cat_rental_requests.order("start_date").each do |req| %>
    <%= render "req_tr", req: req %>
  <% end %>
</table>